### ISSUE TITLE
Improve plug handling UX

### ISSUE THREAD

**Issue by Adimote** [mattconsto/jam#12]
I've seen playtesters:
- Try to drag plugs off to unlink them
- Click on the start plug when holding the end plug to remove the connection
- Click and drag from the socket itself to create a connection

I think we can implement all of these in a single UI so they can pick and choose what to do:
- Start connection if mouse down on an empty socket if nothing in hand
- Stop connection if mouse up on a *different* empty socket with plug in hand
- Move connection if mouse down on occupied socket and drag off.
- Remove connection if mouse up on start socket when moving connection (we'll need to keep a flag for if the connection is being moved or spawned).

**Comment by SThomasP** [comment]
This issue was moved to SThomasP/Dial-Tone#1
